// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDarkMode():Promise<boolean>;

export function GetTime(arg1:string):Promise<number>;

export function GetTransition():Promise<boolean>;

export function SaveConfig():Promise<void>;

export function SetDarkMode(arg1:boolean):Promise<void>;

export function SetTime(arg1:string,arg2:number):Promise<void>;

export function SetTransition(arg1:boolean):Promise<void>;
