// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDarkMode() {
  return window['go']['main']['App']['GetDarkMode']();
}

export function GetTime(arg1) {
  return window['go']['main']['App']['GetTime'](arg1);
}

export function GetTransition() {
  return window['go']['main']['App']['GetTransition']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SetDarkMode(arg1) {
  return window['go']['main']['App']['SetDarkMode'](arg1);
}

export function SetTime(arg1, arg2) {
  return window['go']['main']['App']['SetTime'](arg1, arg2);
}

export function SetTransition(arg1) {
  return window['go']['main']['App']['SetTransition'](arg1);
}
